{% set name = "periscope" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anishathalye/periscope/archive/v{{ version }}.tar.gz
  sha256: 27a7eb749203f1d6be6cb30c6890c4c0a263786a942f6886a2de8c7939d22501

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - psc --help

about:
  home: https://github.com/anishathalye/periscope
  license: GPL-3.0-only
  license_file:
    - LICENSE.txt
    - license-files/
  summary: Organize and de-duplicate your files without losing data
  dev_url: https://github.com/anishathalye/periscope

extra:
  recipe-maintainers:
    - danielnachun
