{% set name = "periscope" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anishathalye/periscope/archive/v{{ version }}.tar.gz
  sha256: a24d349ad89f118245af833af3f50071e85328a6fe084cc6c7f13c771b922271

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - psc --help

about:
  home: https://github.com/anishathalye/periscope
  license: GPL-3.0-only
  license_file:
    - LICENSE.txt
    - license-files/
  summary: Organize and de-duplicate your files without losing data
  dev_url: https://github.com/anishathalye/periscope

extra:
  recipe-maintainers:
    - danielnachun
